name: XCS234_CUDA
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.13
  - notebook=7.2.2
  - tk=8.6.14
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - tensorboard=2.18.0
  - pyyaml=6.0.2
  - pip=24.2
  - pip:
    - setuptools==66.1.1
    - cmake==3.30.5; sys_platform != "win32"
    - wget==3.2; sys_platform != "win32"
    - matplotlib==3.9.2
    - tqdm==4.66.6
    - imageio==2.36.0
    - numpy==2.1.3
    - pandas==2.2.3
    - scipy==1.14.1
    - bottleneck==1.4.2
    - ale-py==0.8.1
    - pygame==2.6.1
    - pyglet==2.0.18
    - autorom[accept-rom-license]==0.6.1
    - dm-control==1.0.25
    - gymnasium[mujoco]==0.29.1
    - stable-baselines3[extra]==2.3.2
    # PyTorch 2.5.x has some issues on MPS device. Therefore we are using for now 2.4.1
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.4.1+cu121
